theme: jekyll-theme-minimal
title: ConControls
author: Ren&eacute; Vogt
description: ConControls is a library for Windows console ui controls.
#url: https://renevogt.github.io/ConControls/
baseurl: ""
markdown: kramdown
